// AUTH
export const AUTH_TOKEN = 'AUTH_TOKEN';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const USER = 'USER';

// FILTER QUERY
export const FILTER_QUERY = 'FILTER_QUERY';
export const RECORDS_REQUEST_QUERY = 'RECORDS_REQUEST_QUERY';
