ansible_connection: local
k8s_namespace: "ratom-{{ env_name }}"
# Only deploy web container from this repo
k8s_templates:
  - name: web.yaml.j2
    state: present

# Disable migrations
k8s_migrations_enabled: false

# App
k8s_container_name: web
k8s_container_image: govsanc/ratom-web
k8s_container_image_tag: latest
k8s_container_resources:
  # Lower resource limits for Nginx, since it doesn't need much
  requests:
    memory: "10Mi"
    cpu: "100m"
k8s_container_port: 80
k8s_container_ingress_paths:
  - /
